spring.application.name=frotacontrol
spring.output.ansi.enabled=ALWAYS

# Configuracoes de upload (vale para todos os ambientes)
spring.servlet.multipart.max-file-size=128MB
spring.servlet.multipart.max-request-size=128MB

# Timezone (se for igual pra todos)
spring.jpa.properties.hibernate.jdbc.time_zone=America/Sao_Paulo

# Specify the path of the OpenAPI documentation
springdoc.api-docs.path=/api-docs


# Banco para desenvolvimento
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/frotacontrol?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC&autoReconnect=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=Waldyr_1966

# Atualiza tabelas sem perder dados
spring.jpa.hibernate.ddl-auto=update

# Mostra SQL no console
#spring.jpa.properties.hibernate.show_sql=true
#spring.jpa.properties.hibernate.format_sql=true

#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=teste@gmail.com
#spring.mail.password=ezadodv
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true


# Ativar Swagger UI no DEV
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tagsSorter=alpha